### ISSUE TITLE
自定义规则传递 ctx

### ISSUE THREAD

**Issue by seekcx** [hexindai/egg-valid#2]
一部分异步验证的需求可能是这样的：

```js
rules: {
  existsPhone: field => options => params => {
    return ctx.service.user.hasPhone(params[field]);
  }
}
```

所以需要在这一块把 `ctx` 给导入进去。

但是实现部分在 

https://github.com/killara/validation/blob/master/lib/validation.js#L34

不知道有啥好办法可以解决。

**Comment by Runrioter** [comment]
Release 4.0.0
